import '../styles/globals.css'
import '../styles/design_tokens.css'
import Layout from '../components/layout'
import Head from 'next/head'
import { AppProps } from 'next/app'

function MyApp({ Component, pageProps }:AppProps) {
  return (
    <>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
        </Head>
        <Layout>
          <Component {...pageProps} />
        </Layout>
    </>
  )
}

export default MyApp
