import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Mateo Garcia Arias
        </h1>

        <p className={styles.description}>
          <h2>web developer</h2>
          
        </p>

        <div className={styles.grid}>
          <a href="/" className={styles.card}>
            <h3>blog</h3>
          </a>

          <a href="/" className={styles.card}>
            
            <h3>mi trabajo</h3>
          </a>

          <a
            href="/"
            className={styles.card}
          >
            <h3>sobre mi</h3>
          </a>

          <a
            href="/"
            className={styles.card}
          >
            <h3>trabaja conmigo</h3>
              
            <p>
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
